postgres:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: password
  PostgresqlDbname: database

redis:
  RedisHost: localhost
  RedisPort: 6379
  RedisUser:
  RedisPassword:
  RedisDB: 0

rabbitmq:
  username: vercello
  password: vercello
  host: localhost
  port: 5672
  exchangeName: tweets-exchange
  queueName: tweets-queue
  consumerTag: tweets-consumer
  bindingKey: tweets-routing-key


minio:
  Endpoint: 127.0.0.1:9000
  MinioAccessKey: minioadmin
  MinioSecretKey: minioadmin
  UseSSL: false

metric:
  jaeger:
    endpoint: http://localhost:14268/api/traces

app:
  port: 3999

